### ISSUE TITLE
Not saving the options

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-lock-membership-level#1]
Unable to save the settings for the "Lock Level" section. Keeps on reverting back to default and unselected.

**Comment by contemplate** [comment]
fixed this here & included your other pull request: https://github.com/strangerstudios/pmpro-lock-membership-level/pull/3

**Comment by annet-lacrimosa** [comment]
when will this fix be deployed? As I understand it is already fixed, but when I check plugin Settings are not saved
