### ISSUE TITLE
Plugin Breaks site: "Error too many redirects"

### ISSUE THREAD

**Issue by anyoakum** [strangerstudios/pmpro-lock-membership-level#4]
Installed the plugin and it "broke" the site, displaying this message:

"This page isn’t working
mpmppia.staging.wpengine.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS"

Disabled the plugin via the database and it restored the site.

**Comment by strangerstudios** [comment]
You need to set a "Locked Page" on the PMPro Page Settings page.

We need to make our documentation more clear.

We also need to catch this error better. In the code, it looks like we try to redirect to the home_url() but that either isn't working or still contributing to a redirect error.

**Comment by andrewlimaza** [comment]
I have done a PR for that here -> https://github.com/strangerstudios/pmpro-lock-membership-level/pull/7

It stops the ERR_TOO_MANY_REDIRECTS when the page isn't setup correctly :)
